// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: raftpb/raftpb.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   uint64                 `protobuf:"varint,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raftpb_raftpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{0}
}

func (x *RequestVoteRequest) GetCandidateId() uint64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteRequest) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVote        bool                   `protobuf:"varint,1,opt,name=isVote,proto3" json:"isVote,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raftpb_raftpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteResponse) GetIsVote() bool {
	if x != nil {
		return x.IsVote
	}
	return false
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Command       []byte                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raftpb_raftpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Leader        int64                  `protobuf:"varint,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,4,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	PreLogIndex   int64                  `protobuf:"varint,5,opt,name=preLogIndex,proto3" json:"preLogIndex,omitempty"`
	PreLogTerm    int64                  `protobuf:"varint,6,opt,name=preLogTerm,proto3" json:"preLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_raftpb_raftpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeader() int64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *AppendEntriesRequest) GetPreLogIndex() int64 {
	if x != nil {
		return x.PreLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPreLogTerm() int64 {
	if x != nil {
		return x.PreLogTerm
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSucess      bool                   `protobuf:"varint,1,opt,name=isSucess,proto3" json:"isSucess,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	ConflictTerm  int64                  `protobuf:"varint,3,opt,name=conflictTerm,proto3" json:"conflictTerm,omitempty"`
	ConflictIndex int64                  `protobuf:"varint,4,opt,name=conflictIndex,proto3" json:"conflictIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raftpb_raftpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesResponse) GetIsSucess() bool {
	if x != nil {
		return x.IsSucess
	}
	return false
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetConflictTerm() int64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *AppendEntriesResponse) GetConflictIndex() int64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

var File_raftpb_raftpb_proto protoreflect.FileDescriptor

const file_raftpb_raftpb_proto_rawDesc = "" +
	"\n" +
	"\x13raftpb/raftpb.proto\x12\x06raftpb\"\x9e\x01\n" +
	"\x12RequestVoteRequest\x12 \n" +
	"\vcandidateId\x18\x01 \x01(\x04R\vcandidateId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x04R\vcurrentTerm\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x04R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x04R\vlastLogTerm\"A\n" +
	"\x13RequestVoteResponse\x12\x16\n" +
	"\x06isVote\x18\x01 \x01(\bR\x06isVote\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x04R\x04Term\"N\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x18\n" +
	"\acommand\x18\x03 \x01(\fR\acommand\"\xd4\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x16\n" +
	"\x06Leader\x18\x02 \x01(\x03R\x06Leader\x12*\n" +
	"\aentries\x18\x03 \x03(\v2\x10.raftpb.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x04 \x01(\x03R\fleaderCommit\x12 \n" +
	"\vpreLogIndex\x18\x05 \x01(\x03R\vpreLogIndex\x12\x1e\n" +
	"\n" +
	"preLogTerm\x18\x06 \x01(\x03R\n" +
	"preLogTerm\"\x91\x01\n" +
	"\x15AppendEntriesResponse\x12\x1a\n" +
	"\bisSucess\x18\x01 \x01(\bR\bisSucess\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\"\n" +
	"\fconflictTerm\x18\x03 \x01(\x03R\fconflictTerm\x12$\n" +
	"\rconflictIndex\x18\x04 \x01(\x03R\rconflictIndex2\x9c\x01\n" +
	"\x04Raft\x12L\n" +
	"\rAppendEntries\x12\x1c.raftpb.AppendEntriesRequest\x1a\x1d.raftpb.AppendEntriesResponse\x12F\n" +
	"\vRequestVote\x12\x1a.raftpb.RequestVoteRequest\x1a\x1b.raftpb.RequestVoteResponseB%Z#github.com/zbchi/linkv/proto/raftpbb\x06proto3"

var (
	file_raftpb_raftpb_proto_rawDescOnce sync.Once
	file_raftpb_raftpb_proto_rawDescData []byte
)

func file_raftpb_raftpb_proto_rawDescGZIP() []byte {
	file_raftpb_raftpb_proto_rawDescOnce.Do(func() {
		file_raftpb_raftpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftpb_raftpb_proto_rawDesc), len(file_raftpb_raftpb_proto_rawDesc)))
	})
	return file_raftpb_raftpb_proto_rawDescData
}

var file_raftpb_raftpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_raftpb_raftpb_proto_goTypes = []any{
	(*RequestVoteRequest)(nil),    // 0: raftpb.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 1: raftpb.RequestVoteResponse
	(*LogEntry)(nil),              // 2: raftpb.LogEntry
	(*AppendEntriesRequest)(nil),  // 3: raftpb.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 4: raftpb.AppendEntriesResponse
}
var file_raftpb_raftpb_proto_depIdxs = []int32{
	2, // 0: raftpb.AppendEntriesRequest.entries:type_name -> raftpb.LogEntry
	3, // 1: raftpb.Raft.AppendEntries:input_type -> raftpb.AppendEntriesRequest
	0, // 2: raftpb.Raft.RequestVote:input_type -> raftpb.RequestVoteRequest
	4, // 3: raftpb.Raft.AppendEntries:output_type -> raftpb.AppendEntriesResponse
	1, // 4: raftpb.Raft.RequestVote:output_type -> raftpb.RequestVoteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raftpb_raftpb_proto_init() }
func file_raftpb_raftpb_proto_init() {
	if File_raftpb_raftpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftpb_raftpb_proto_rawDesc), len(file_raftpb_raftpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raftpb_raftpb_proto_goTypes,
		DependencyIndexes: file_raftpb_raftpb_proto_depIdxs,
		MessageInfos:      file_raftpb_raftpb_proto_msgTypes,
	}.Build()
	File_raftpb_raftpb_proto = out.File
	file_raftpb_raftpb_proto_goTypes = nil
	file_raftpb_raftpb_proto_depIdxs = nil
}
