// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: raftpb/raftpb.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Type int32

const (
	Message_MsgHup      Message_Type = 0
	Message_MsgBeat     Message_Type = 1
	Message_MsgApp      Message_Type = 2
	Message_MsgAppResp  Message_Type = 3
	Message_MsgVote     Message_Type = 4
	Message_MsgVoteResp Message_Type = 5
	Message_MsgSnap     Message_Type = 6
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "MsgHup",
		1: "MsgBeat",
		2: "MsgApp",
		3: "MsgAppResp",
		4: "MsgVote",
		5: "MsgVoteResp",
		6: "MsgSnap",
	}
	Message_Type_value = map[string]int32{
		"MsgHup":      0,
		"MsgBeat":     1,
		"MsgApp":      2,
		"MsgAppResp":  3,
		"MsgVote":     4,
		"MsgVoteResp": 5,
		"MsgSnap":     6,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_raftpb_raftpb_proto_enumTypes[0].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_raftpb_raftpb_proto_enumTypes[0]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{1, 0}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raftpb_raftpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Message_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.Message_Type" json:"type,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,5,opt,name=logTerm,proto3" json:"logTerm,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,6,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	Commit        uint64                 `protobuf:"varint,7,opt,name=commit,proto3" json:"commit,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"`
	Reject        bool                   `protobuf:"varint,9,opt,name=reject,proto3" json:"reject,omitempty"`
	RejectHint    uint64                 `protobuf:"varint,10,opt,name=rejectHint,proto3" json:"rejectHint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_raftpb_raftpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raftpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_raftpb_raftpb_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() Message_Type {
	if x != nil {
		return x.Type
	}
	return Message_MsgHup
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *Message) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *Message) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *Message) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *Message) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

var File_raftpb_raftpb_proto protoreflect.FileDescriptor

const file_raftpb_raftpb_proto_rawDesc = "" +
	"\n" +
	"\x13raftpb/raftpb.proto\x12\x06raftpb\"E\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x82\x03\n" +
	"\aMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.raftpb.Message.TypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x18\n" +
	"\alogTerm\x18\x05 \x01(\x04R\alogTerm\x12\x1a\n" +
	"\blogIndex\x18\x06 \x01(\x04R\blogIndex\x12\x16\n" +
	"\x06commit\x18\a \x01(\x04R\x06commit\x12'\n" +
	"\aentries\x18\b \x03(\v2\r.raftpb.EntryR\aentries\x12\x16\n" +
	"\x06reject\x18\t \x01(\bR\x06reject\x12\x1e\n" +
	"\n" +
	"rejectHint\x18\n" +
	" \x01(\x04R\n" +
	"rejectHint\"f\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06MsgHup\x10\x00\x12\v\n" +
	"\aMsgBeat\x10\x01\x12\n" +
	"\n" +
	"\x06MsgApp\x10\x02\x12\x0e\n" +
	"\n" +
	"MsgAppResp\x10\x03\x12\v\n" +
	"\aMsgVote\x10\x04\x12\x0f\n" +
	"\vMsgVoteResp\x10\x05\x12\v\n" +
	"\aMsgSnap\x10\x0620\n" +
	"\x04Raft\x12(\n" +
	"\x04Step\x12\x0f.raftpb.Message\x1a\x0f.raftpb.MessageB%Z#github.com/zbchi/linkv/proto/raftpbb\x06proto3"

var (
	file_raftpb_raftpb_proto_rawDescOnce sync.Once
	file_raftpb_raftpb_proto_rawDescData []byte
)

func file_raftpb_raftpb_proto_rawDescGZIP() []byte {
	file_raftpb_raftpb_proto_rawDescOnce.Do(func() {
		file_raftpb_raftpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftpb_raftpb_proto_rawDesc), len(file_raftpb_raftpb_proto_rawDesc)))
	})
	return file_raftpb_raftpb_proto_rawDescData
}

var file_raftpb_raftpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raftpb_raftpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raftpb_raftpb_proto_goTypes = []any{
	(Message_Type)(0), // 0: raftpb.Message.Type
	(*Entry)(nil),     // 1: raftpb.Entry
	(*Message)(nil),   // 2: raftpb.Message
}
var file_raftpb_raftpb_proto_depIdxs = []int32{
	0, // 0: raftpb.Message.type:type_name -> raftpb.Message.Type
	1, // 1: raftpb.Message.entries:type_name -> raftpb.Entry
	2, // 2: raftpb.Raft.Step:input_type -> raftpb.Message
	2, // 3: raftpb.Raft.Step:output_type -> raftpb.Message
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raftpb_raftpb_proto_init() }
func file_raftpb_raftpb_proto_init() {
	if File_raftpb_raftpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftpb_raftpb_proto_rawDesc), len(file_raftpb_raftpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raftpb_raftpb_proto_goTypes,
		DependencyIndexes: file_raftpb_raftpb_proto_depIdxs,
		EnumInfos:         file_raftpb_raftpb_proto_enumTypes,
		MessageInfos:      file_raftpb_raftpb_proto_msgTypes,
	}.Build()
	File_raftpb_raftpb_proto = out.File
	file_raftpb_raftpb_proto_goTypes = nil
	file_raftpb_raftpb_proto_depIdxs = nil
}
