// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: linkv.proto

package linkvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Linkv_RawGet_FullMethodName    = "/linkvpb.Linkv/RawGet"
	Linkv_RawPut_FullMethodName    = "/linkvpb.Linkv/RawPut"
	Linkv_RawDelete_FullMethodName = "/linkvpb.Linkv/RawDelete"
	Linkv_RawScan_FullMethodName   = "/linkvpb.Linkv/RawScan"
)

// LinkvClient is the client API for Linkv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkvClient interface {
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
	RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error)
}

type linkvClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkvClient(cc grpc.ClientConnInterface) LinkvClient {
	return &linkvClient{cc}
}

func (c *linkvClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, Linkv_RawGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkvClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, Linkv_RawPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkvClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, Linkv_RawDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkvClient) RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawScanResponse)
	err := c.cc.Invoke(ctx, Linkv_RawScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkvServer is the server API for Linkv service.
// All implementations must embed UnimplementedLinkvServer
// for forward compatibility.
type LinkvServer interface {
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
	RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error)
	mustEmbedUnimplementedLinkvServer()
}

// UnimplementedLinkvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkvServer struct{}

func (UnimplementedLinkvServer) RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (UnimplementedLinkvServer) RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (UnimplementedLinkvServer) RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}
func (UnimplementedLinkvServer) RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawScan not implemented")
}
func (UnimplementedLinkvServer) mustEmbedUnimplementedLinkvServer() {}
func (UnimplementedLinkvServer) testEmbeddedByValue()               {}

// UnsafeLinkvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkvServer will
// result in compilation errors.
type UnsafeLinkvServer interface {
	mustEmbedUnimplementedLinkvServer()
}

func RegisterLinkvServer(s grpc.ServiceRegistrar, srv LinkvServer) {
	// If the following call pancis, it indicates UnimplementedLinkvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Linkv_ServiceDesc, srv)
}

func _Linkv_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkvServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Linkv_RawGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkvServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Linkv_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkvServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Linkv_RawPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkvServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Linkv_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkvServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Linkv_RawDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkvServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Linkv_RawScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkvServer).RawScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Linkv_RawScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkvServer).RawScan(ctx, req.(*RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Linkv_ServiceDesc is the grpc.ServiceDesc for Linkv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Linkv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkvpb.Linkv",
	HandlerType: (*LinkvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _Linkv_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _Linkv_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _Linkv_RawDelete_Handler,
		},
		{
			MethodName: "RawScan",
			Handler:    _Linkv_RawScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "linkv.proto",
}
