// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: linkv.proto

package linkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_linkv_proto protoreflect.FileDescriptor

const file_linkv_proto_rawDesc = "" +
	"\n" +
	"\vlinkv.proto\x12\alinkvpb\x1a\rkvrpcpb.proto2\xff\x01\n" +
	"\x05Linkv\x129\n" +
	"\x06RawGet\x12\x16.kvrpcpb.RawGetRequest\x1a\x17.kvrpcpb.RawGetResponse\x129\n" +
	"\x06RawPut\x12\x16.kvrpcpb.RawPutRequest\x1a\x17.kvrpcpb.RawPutResponse\x12B\n" +
	"\tRawDelete\x12\x19.kvrpcpb.RawDeleteRequest\x1a\x1a.kvrpcpb.RawDeleteResponse\x12<\n" +
	"\aRawScan\x12\x17.kvrpcpb.RawScanRequest\x1a\x18.kvrpcpb.RawScanResponseB2Z0github.com/zbchi/linkv/proto/pkg/linkvpb;linkvpbb\x06proto3"

var file_linkv_proto_goTypes = []any{
	(*RawGetRequest)(nil),     // 0: kvrpcpb.RawGetRequest
	(*RawPutRequest)(nil),     // 1: kvrpcpb.RawPutRequest
	(*RawDeleteRequest)(nil),  // 2: kvrpcpb.RawDeleteRequest
	(*RawScanRequest)(nil),    // 3: kvrpcpb.RawScanRequest
	(*RawGetResponse)(nil),    // 4: kvrpcpb.RawGetResponse
	(*RawPutResponse)(nil),    // 5: kvrpcpb.RawPutResponse
	(*RawDeleteResponse)(nil), // 6: kvrpcpb.RawDeleteResponse
	(*RawScanResponse)(nil),   // 7: kvrpcpb.RawScanResponse
}
var file_linkv_proto_depIdxs = []int32{
	0, // 0: linkvpb.Linkv.RawGet:input_type -> kvrpcpb.RawGetRequest
	1, // 1: linkvpb.Linkv.RawPut:input_type -> kvrpcpb.RawPutRequest
	2, // 2: linkvpb.Linkv.RawDelete:input_type -> kvrpcpb.RawDeleteRequest
	3, // 3: linkvpb.Linkv.RawScan:input_type -> kvrpcpb.RawScanRequest
	4, // 4: linkvpb.Linkv.RawGet:output_type -> kvrpcpb.RawGetResponse
	5, // 5: linkvpb.Linkv.RawPut:output_type -> kvrpcpb.RawPutResponse
	6, // 6: linkvpb.Linkv.RawDelete:output_type -> kvrpcpb.RawDeleteResponse
	7, // 7: linkvpb.Linkv.RawScan:output_type -> kvrpcpb.RawScanResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_linkv_proto_init() }
func file_linkv_proto_init() {
	if File_linkv_proto != nil {
		return
	}
	file_kvrpcpb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_linkv_proto_rawDesc), len(file_linkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkv_proto_goTypes,
		DependencyIndexes: file_linkv_proto_depIdxs,
	}.Build()
	File_linkv_proto = out.File
	file_linkv_proto_goTypes = nil
	file_linkv_proto_depIdxs = nil
}
