// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: linkvpb/linkv.proto

package linkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_linkvpb_linkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{0}
}

type RawGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetRequest) Reset() {
	*x = RawGetRequest{}
	mi := &file_linkvpb_linkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetRequest) ProtoMessage() {}

func (x *RawGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetRequest.ProtoReflect.Descriptor instead.
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{1}
}

func (x *RawGetRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawGetRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetResponse) Reset() {
	*x = RawGetResponse{}
	mi := &file_linkvpb_linkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetResponse) ProtoMessage() {}

func (x *RawGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetResponse.ProtoReflect.Descriptor instead.
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{2}
}

func (x *RawGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutRequest) Reset() {
	*x = RawPutRequest{}
	mi := &file_linkvpb_linkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutRequest) ProtoMessage() {}

func (x *RawPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutRequest.ProtoReflect.Descriptor instead.
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{3}
}

func (x *RawPutRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawPutRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutResponse) Reset() {
	*x = RawPutResponse{}
	mi := &file_linkvpb_linkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutResponse) ProtoMessage() {}

func (x *RawPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutResponse.ProtoReflect.Descriptor instead.
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{4}
}

type RawDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteRequest) Reset() {
	*x = RawDeleteRequest{}
	mi := &file_linkvpb_linkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteRequest) ProtoMessage() {}

func (x *RawDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteRequest.ProtoReflect.Descriptor instead.
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{5}
}

func (x *RawDeleteRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawDeleteRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteResponse) Reset() {
	*x = RawDeleteResponse{}
	mi := &file_linkvpb_linkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteResponse) ProtoMessage() {}

func (x *RawDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteResponse.ProtoReflect.Descriptor instead.
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{6}
}

type RawScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanRequest) Reset() {
	*x = RawScanRequest{}
	mi := &file_linkvpb_linkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanRequest) ProtoMessage() {}

func (x *RawScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanRequest.ProtoReflect.Descriptor instead.
func (*RawScanRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{7}
}

func (x *RawScanRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawScanRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RawScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RawScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*KvPair              `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanResponse) Reset() {
	*x = RawScanResponse{}
	mi := &file_linkvpb_linkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanResponse) ProtoMessage() {}

func (x *RawScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanResponse.ProtoReflect.Descriptor instead.
func (*RawScanResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{8}
}

func (x *RawScanResponse) GetPairs() []*KvPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type KvPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPair) Reset() {
	*x = KvPair{}
	mi := &file_linkvpb_linkv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPair) ProtoMessage() {}

func (x *KvPair) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPair.ProtoReflect.Descriptor instead.
func (*KvPair) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{9}
}

func (x *KvPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_linkvpb_linkv_proto protoreflect.FileDescriptor

const file_linkvpb_linkv_proto_rawDesc = "" +
	"\n" +
	"\x13linkvpb/linkv.proto\x12\alinkvpb\"\t\n" +
	"\aContext\"]\n" +
	"\rRawGetRequest\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.linkvpb.ContextR\acontext\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"&\n" +
	"\x0eRawGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"s\n" +
	"\rRawPutRequest\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.linkvpb.ContextR\acontext\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"\x10\n" +
	"\x0eRawPutResponse\"`\n" +
	"\x10RawDeleteRequest\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.linkvpb.ContextR\acontext\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"\x13\n" +
	"\x11RawDeleteResponse\"\x7f\n" +
	"\x0eRawScanRequest\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.linkvpb.ContextR\acontext\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x1b\n" +
	"\tstart_key\x18\x03 \x01(\fR\bstartKey\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"8\n" +
	"\x0fRawScanResponse\x12%\n" +
	"\x05pairs\x18\x01 \x03(\v2\x0f.linkvpb.KvPairR\x05pairs\"0\n" +
	"\x06KvPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\xff\x01\n" +
	"\x05Linkv\x129\n" +
	"\x06RawGet\x12\x16.linkvpb.RawGetRequest\x1a\x17.linkvpb.RawGetResponse\x129\n" +
	"\x06RawPut\x12\x16.linkvpb.RawPutRequest\x1a\x17.linkvpb.RawPutResponse\x12B\n" +
	"\tRawDelete\x12\x19.linkvpb.RawDeleteRequest\x1a\x1a.linkvpb.RawDeleteResponse\x12<\n" +
	"\aRawScan\x12\x17.linkvpb.RawScanRequest\x1a\x18.linkvpb.RawScanResponseB&Z$github.com/zbchi/linkv/proto/linkvpbb\x06proto3"

var (
	file_linkvpb_linkv_proto_rawDescOnce sync.Once
	file_linkvpb_linkv_proto_rawDescData []byte
)

func file_linkvpb_linkv_proto_rawDescGZIP() []byte {
	file_linkvpb_linkv_proto_rawDescOnce.Do(func() {
		file_linkvpb_linkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_linkvpb_linkv_proto_rawDesc), len(file_linkvpb_linkv_proto_rawDesc)))
	})
	return file_linkvpb_linkv_proto_rawDescData
}

var file_linkvpb_linkv_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_linkvpb_linkv_proto_goTypes = []any{
	(*Context)(nil),           // 0: linkvpb.Context
	(*RawGetRequest)(nil),     // 1: linkvpb.RawGetRequest
	(*RawGetResponse)(nil),    // 2: linkvpb.RawGetResponse
	(*RawPutRequest)(nil),     // 3: linkvpb.RawPutRequest
	(*RawPutResponse)(nil),    // 4: linkvpb.RawPutResponse
	(*RawDeleteRequest)(nil),  // 5: linkvpb.RawDeleteRequest
	(*RawDeleteResponse)(nil), // 6: linkvpb.RawDeleteResponse
	(*RawScanRequest)(nil),    // 7: linkvpb.RawScanRequest
	(*RawScanResponse)(nil),   // 8: linkvpb.RawScanResponse
	(*KvPair)(nil),            // 9: linkvpb.KvPair
}
var file_linkvpb_linkv_proto_depIdxs = []int32{
	0, // 0: linkvpb.RawGetRequest.context:type_name -> linkvpb.Context
	0, // 1: linkvpb.RawPutRequest.context:type_name -> linkvpb.Context
	0, // 2: linkvpb.RawDeleteRequest.context:type_name -> linkvpb.Context
	0, // 3: linkvpb.RawScanRequest.context:type_name -> linkvpb.Context
	9, // 4: linkvpb.RawScanResponse.pairs:type_name -> linkvpb.KvPair
	1, // 5: linkvpb.Linkv.RawGet:input_type -> linkvpb.RawGetRequest
	3, // 6: linkvpb.Linkv.RawPut:input_type -> linkvpb.RawPutRequest
	5, // 7: linkvpb.Linkv.RawDelete:input_type -> linkvpb.RawDeleteRequest
	7, // 8: linkvpb.Linkv.RawScan:input_type -> linkvpb.RawScanRequest
	2, // 9: linkvpb.Linkv.RawGet:output_type -> linkvpb.RawGetResponse
	4, // 10: linkvpb.Linkv.RawPut:output_type -> linkvpb.RawPutResponse
	6, // 11: linkvpb.Linkv.RawDelete:output_type -> linkvpb.RawDeleteResponse
	8, // 12: linkvpb.Linkv.RawScan:output_type -> linkvpb.RawScanResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_linkvpb_linkv_proto_init() }
func file_linkvpb_linkv_proto_init() {
	if File_linkvpb_linkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_linkvpb_linkv_proto_rawDesc), len(file_linkvpb_linkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkvpb_linkv_proto_goTypes,
		DependencyIndexes: file_linkvpb_linkv_proto_depIdxs,
		MessageInfos:      file_linkvpb_linkv_proto_msgTypes,
	}.Build()
	File_linkvpb_linkv_proto = out.File
	file_linkvpb_linkv_proto_goTypes = nil
	file_linkvpb_linkv_proto_depIdxs = nil
}
