// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: linkvpb/linkv.proto

package linkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{0}
}

type RawGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf      string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key     []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RawGetRequest) Reset() {
	*x = RawGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetRequest) ProtoMessage() {}

func (x *RawGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetRequest.ProtoReflect.Descriptor instead.
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{1}
}

func (x *RawGetRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawGetRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RawGetResponse) Reset() {
	*x = RawGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetResponse) ProtoMessage() {}

func (x *RawGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetResponse.ProtoReflect.Descriptor instead.
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{2}
}

func (x *RawGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf      string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key     []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RawPutRequest) Reset() {
	*x = RawPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutRequest) ProtoMessage() {}

func (x *RawPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutRequest.ProtoReflect.Descriptor instead.
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{3}
}

func (x *RawPutRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawPutRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawPutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RawPutResponse) Reset() {
	*x = RawPutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutResponse) ProtoMessage() {}

func (x *RawPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutResponse.ProtoReflect.Descriptor instead.
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{4}
}

type RawDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf      string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key     []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RawDeleteRequest) Reset() {
	*x = RawDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteRequest) ProtoMessage() {}

func (x *RawDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteRequest.ProtoReflect.Descriptor instead.
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{5}
}

func (x *RawDeleteRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawDeleteRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RawDeleteResponse) Reset() {
	*x = RawDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteResponse) ProtoMessage() {}

func (x *RawDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteResponse.ProtoReflect.Descriptor instead.
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{6}
}

type RawScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context  *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Cf       string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	StartKey []byte   `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit    uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RawScanRequest) Reset() {
	*x = RawScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanRequest) ProtoMessage() {}

func (x *RawScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanRequest.ProtoReflect.Descriptor instead.
func (*RawScanRequest) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{7}
}

func (x *RawScanRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RawScanRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RawScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RawScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RawScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*KvPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *RawScanResponse) Reset() {
	*x = RawScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanResponse) ProtoMessage() {}

func (x *RawScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanResponse.ProtoReflect.Descriptor instead.
func (*RawScanResponse) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{8}
}

func (x *RawScanResponse) GetPairs() []*KvPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type KvPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KvPair) Reset() {
	*x = KvPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkvpb_linkv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPair) ProtoMessage() {}

func (x *KvPair) ProtoReflect() protoreflect.Message {
	mi := &file_linkvpb_linkv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPair.ProtoReflect.Descriptor instead.
func (*KvPair) Descriptor() ([]byte, []int) {
	return file_linkvpb_linkv_proto_rawDescGZIP(), []int{9}
}

func (x *KvPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_linkvpb_linkv_proto protoreflect.FileDescriptor

var file_linkvpb_linkv_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x22, 0x09,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5d, 0x0a, 0x0d, 0x52, 0x61, 0x77,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x63, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x52, 0x61, 0x77, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x73, 0x0a, 0x0d, 0x52, 0x61, 0x77, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x63, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x66, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x61, 0x77, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x10, 0x52, 0x61, 0x77, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x61, 0x77,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f,
	0x0a, 0x0e, 0x52, 0x61, 0x77, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x63, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x66, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x38, 0x0a, 0x0f, 0x52, 0x61, 0x77, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x4b, 0x76, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x4b, 0x76, 0x50,
	0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xff, 0x01, 0x0a, 0x05,
	0x4c, 0x69, 0x6e, 0x6b, 0x76, 0x12, 0x39, 0x0a, 0x06, 0x52, 0x61, 0x77, 0x47, 0x65, 0x74, 0x12,
	0x16, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70,
	0x62, 0x2e, 0x52, 0x61, 0x77, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x06, 0x52, 0x61, 0x77, 0x50, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x52,
	0x61, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76,
	0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61,
	0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x07, 0x52, 0x61, 0x77, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x17, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61,
	0x77, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x62, 0x63, 0x68,
	0x69, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69,
	0x6e, 0x6b, 0x76, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linkvpb_linkv_proto_rawDescOnce sync.Once
	file_linkvpb_linkv_proto_rawDescData = file_linkvpb_linkv_proto_rawDesc
)

func file_linkvpb_linkv_proto_rawDescGZIP() []byte {
	file_linkvpb_linkv_proto_rawDescOnce.Do(func() {
		file_linkvpb_linkv_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkvpb_linkv_proto_rawDescData)
	})
	return file_linkvpb_linkv_proto_rawDescData
}

var file_linkvpb_linkv_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_linkvpb_linkv_proto_goTypes = []interface{}{
	(*Context)(nil),           // 0: linkvpb.Context
	(*RawGetRequest)(nil),     // 1: linkvpb.RawGetRequest
	(*RawGetResponse)(nil),    // 2: linkvpb.RawGetResponse
	(*RawPutRequest)(nil),     // 3: linkvpb.RawPutRequest
	(*RawPutResponse)(nil),    // 4: linkvpb.RawPutResponse
	(*RawDeleteRequest)(nil),  // 5: linkvpb.RawDeleteRequest
	(*RawDeleteResponse)(nil), // 6: linkvpb.RawDeleteResponse
	(*RawScanRequest)(nil),    // 7: linkvpb.RawScanRequest
	(*RawScanResponse)(nil),   // 8: linkvpb.RawScanResponse
	(*KvPair)(nil),            // 9: linkvpb.KvPair
}
var file_linkvpb_linkv_proto_depIdxs = []int32{
	0, // 0: linkvpb.RawGetRequest.context:type_name -> linkvpb.Context
	0, // 1: linkvpb.RawPutRequest.context:type_name -> linkvpb.Context
	0, // 2: linkvpb.RawDeleteRequest.context:type_name -> linkvpb.Context
	0, // 3: linkvpb.RawScanRequest.context:type_name -> linkvpb.Context
	9, // 4: linkvpb.RawScanResponse.pairs:type_name -> linkvpb.KvPair
	1, // 5: linkvpb.Linkv.RawGet:input_type -> linkvpb.RawGetRequest
	3, // 6: linkvpb.Linkv.RawPut:input_type -> linkvpb.RawPutRequest
	5, // 7: linkvpb.Linkv.RawDelete:input_type -> linkvpb.RawDeleteRequest
	7, // 8: linkvpb.Linkv.RawScan:input_type -> linkvpb.RawScanRequest
	2, // 9: linkvpb.Linkv.RawGet:output_type -> linkvpb.RawGetResponse
	4, // 10: linkvpb.Linkv.RawPut:output_type -> linkvpb.RawPutResponse
	6, // 11: linkvpb.Linkv.RawDelete:output_type -> linkvpb.RawDeleteResponse
	8, // 12: linkvpb.Linkv.RawScan:output_type -> linkvpb.RawScanResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_linkvpb_linkv_proto_init() }
func file_linkvpb_linkv_proto_init() {
	if File_linkvpb_linkv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkvpb_linkv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawPutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkvpb_linkv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkvpb_linkv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkvpb_linkv_proto_goTypes,
		DependencyIndexes: file_linkvpb_linkv_proto_depIdxs,
		MessageInfos:      file_linkvpb_linkv_proto_msgTypes,
	}.Build()
	File_linkvpb_linkv_proto = out.File
	file_linkvpb_linkv_proto_rawDesc = nil
	file_linkvpb_linkv_proto_goTypes = nil
	file_linkvpb_linkv_proto_depIdxs = nil
}
